apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: "kafka"
  name: datadir
  labels:
      app: zookeeper
      release: xonic
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp
