apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "xonic-api-be"
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "xonic-api-be"
    spec:
      hostNetwork: false
      containers:
      - name: xonic-api-be
        image: nexus.gdmlabs.net:5000/xonic-api-be:latest  # or just image: redis
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: desa
        resources:
          requests:
            cpu: 200m
            memory: 1024Mi
        imagePullPolicy: "IfNotPresent"
        ports:
            - containerPort: 18080
        volumeMounts:
            - mountPath: "/log"
              name: api-be-data
      volumes:
        - name: api-be-data
          persistentVolumeClaim:
            claimName: api-be-data

