apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: "kafka"
  name: kafka-data
  labels:
      app: kafka
      release: xonic
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp
