apiVersion: v1
kind: Service
metadata:
  name: "xonic-mysql-svc"
  namespace: default
  labels:
    app: "xonic-mysql-svc"
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - name: "mysql-devx"
      port: 33060
      nodePort: 31060
    - name: "mysql-std"
      port: 3306
      targetPort: 3306
      nodePort: 31160
  selector:
        app: xonic-mysql
 
