apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: mysql-rds-data
  labels:
      app: xonic-rd-mysql
      release: xonic-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
