apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: "default"
  name: mysql-data
  labels:
      app: xonic-rd-mysql
      release: xonic-mysql
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /opt/mysql
