apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: api-gtw-storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/api-gtw/logs
