apiVersion: v1
kind: Service
metadata:
  name: "xonic-api-gtw-svc"
  namespace: default
  labels:
    app: "xonic-api-gtw-svc"
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 28080
      targetPort: 28080
  selector:
    app: xonic-api-gtw
